#!/usr/bin/env bash
# Regenerate the nftables set of AS12912 (T-Mobile Polska) announced IPv4
# prefixes, which gate access to the k3s API server on 6443.
#
# The allowlist is deliberately wide: the operator's egress address is
# carrier-assigned, so a narrower rule risks a lockout. That is recorded as
# debt item D-01 (narrow-cluster-api-allowlist) in the project roadmap.
# BGP announcements drift, so this must run periodically or the set rots.
set -euo pipefail

ASN="AS12912"
OUT="/etc/nftables.d/as12912.nft"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

PREFIXES="$(curl -fsS --max-time 30 \
  "https://stat.ripe.net/data/announced-prefixes/data.json?resource=${ASN}" \
  | python3 -c '
import sys, json
d = json.load(sys.stdin)["data"]
v4 = [p["prefix"] for p in d.get("prefixes", []) if ":" not in p["prefix"]]
if not v4:
    sys.exit("no IPv4 prefixes returned")
print(", ".join(sorted(set(v4))))
')"

{
  echo "# Generated by $(basename "$0") on $(date -u +%FT%TZ) - do not edit by hand."
  echo "# Source: RIPEstat announced-prefixes for ${ASN}."
  echo "add element inet filter as12912_v4 { ${PREFIXES} }"
} > "$TMP"

install -m 0644 "$TMP" "$OUT"

# Reload just this set, never the whole ruleset.
if nft list set inet filter as12912_v4 >/dev/null 2>&1; then
  nft flush set inet filter as12912_v4
  nft -f "$OUT"
fi

echo "Refreshed ${OUT}: $(grep -o '/[0-9]\+' "$OUT" | wc -l) prefixes."
